export class ACTIONS {
  static ACCOUNT_ADDED = "ACCOUNT_ADDED";
  static GET_ACCOUNTS = "GET_ACCOUNTS";
  static GET_ACCOUNTS_DONE = "GET_ACCOUNTS_DONE";
  static GET_TRANSACTIONS = "GET_TRANSACTIONS";
  static INIT = "INIT";
  static DELETE_ACCOUNT_DONE = "DELETE_ACCOUNT_DONE";
  static DELETE_ACCOUNT = "DELETE_ACCOUNT";
  static UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
}
